package booking.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "BookingServiceImpl", targetNamespace = "http://service.booking/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface BookingServiceImpl {


    /**
     * @param arg1
     * @param arg0
     * @return returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.booking/BookingServiceImpl/bookedTicketRequest", output = "http://service.booking/BookingServiceImpl/bookedTicketResponse")
    public int bookedTicket(
            @WebParam(name = "arg0", partName = "arg0")
            int arg0,
            @WebParam(name = "arg1", partName = "arg1")
            Person arg1);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.booking/BookingServiceImpl/getTicketsRequest", output = "http://service.booking/BookingServiceImpl/getTicketsResponse")
    public String getTickets(
            @WebParam(name = "arg0", partName = "arg0")
            int arg0);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.booking/BookingServiceImpl/getAllTicketsRequest", output = "http://service.booking/BookingServiceImpl/getAllTicketsResponse")
    public String getAllTickets();

    /**
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.booking/BookingServiceImpl/payTicketRequest", output = "http://service.booking/BookingServiceImpl/payTicketResponse")
    public void payTicket(
            @WebParam(name = "arg0", partName = "arg0")
            int arg0);

    /**
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.booking/BookingServiceImpl/removeTicketRequest", output = "http://service.booking/BookingServiceImpl/removeTicketResponse")
    public void removeTicket(
            @WebParam(name = "arg0", partName = "arg0")
            int arg0);

}
