
package booking.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookingServiceImplService", targetNamespace = "http://impl.service.booking/", wsdlLocation = "http://localhost:8088/booking?wsdl")
public class BookingServiceImplService
    extends Service
{

    private final static URL BOOKINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKINGSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BOOKINGSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.booking/", "BookingServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/booking?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKINGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BOOKINGSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BookingServiceImplService() {
        super(__getWsdlLocation(), BOOKINGSERVICEIMPLSERVICE_QNAME);
    }

    public BookingServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public BookingServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BOOKINGSERVICEIMPLSERVICE_QNAME);
    }

    public BookingServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public BookingServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookingServiceImpl
     */
    @WebEndpoint(name = "BookingServiceImplPort")
    public BookingServiceImpl getBookingServiceImplPort() {
        return super.getPort(new QName("http://impl.service.booking/", "BookingServiceImplPort"), BookingServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookingServiceImpl
     */
    @WebEndpoint(name = "BookingServiceImplPort")
    public BookingServiceImpl getBookingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.booking/", "BookingServiceImplPort"), BookingServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKINGSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BOOKINGSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BOOKINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
