package booking.service.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "BookingError", targetNamespace = "http://impl.service.booking/")
public class BookingError_Exception
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private BookingError faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public BookingError_Exception(String message, BookingError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BookingError_Exception(String message, BookingError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: booking.service.impl.BookingError
     */
    public BookingError getFaultInfo() {
        return faultInfo;
    }

}
